# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
        # Label used to access the service container
        postgres:
          # Docker Hub image
          image: postgres:16
          # Provide the password for postgres
          env:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: simple_bank

          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install sqlc
      run: |
        curl -L https://downloads.sqlc.dev/sqlc_1.25.0_linux_amd64.tar.gz | gunzip | tar xvf -
        sudo mv sqlc /usr/bin

    - name: Generate sqlc files
      run: make sqlc

    - name: Run mockgen
      run: |
        go install github.com/golang/mock/mockgen@v1.6.0
        make mock

    - name: Download migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin

    - name: Run migration
      run: make migrateup

    - name: Install protoc
      run: |
        echo "*** unzipping protoc"
        curl -L --output protoc-26.1-linux-x86_64.zip https://github.com/protocolbuffers/protobuf/releases/download/v26.1/protoc-26.1-linux-x86_64.zip
        unzip protoc-26.1-linux-x86_64.zip bin/protoc
        echo "*** moving bin/protoc /usr/bin"
        sudo mv bin/protoc /usr/bin
        echo "*** moving proto files to /usr/include"
        sudo mkdir -p /usr/include/google/protobuf
        sudo mv include/*.proto /usr/include/google/protobuf

    - name: Install go protoc and grpc plugins
      run: | 
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest

    - name: Generate go files from protobuf specs.
      run: |
        make proto

    - name: Test
      run: make tests